name: plezy
description: "A beautiful Plex client for Flutter"
publish_to: "none"
version: 1.15.0+36

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.4.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  window_manager: ^0.4.3
  logger: ^2.0.2
  package_info_plus: ^9.0.0
  device_info_plus: ^11.0.0
  provider: ^6.1.2
  hotkey_manager: ^0.2.3
  flex_color_picker: ^3.6.0
  qr_flutter: ^4.1.0
  slang: ^4.12.0
  slang_flutter: ^4.12.0
  duration: ^4.0.3
  connectivity_plus: ^6.0.5
  os_media_controls:
    git:
      url: https://github.com/edde746/os-media-controls
      ref: 6463fd18875ead347e739189b9687307f629f090
  rate_limiter: ^1.0.0
  wakelock_plus: ^1.2.10
  path_provider: ^2.1.0
  path: ^1.9.0
  gamepads: ^0.1.9
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.41
  workmanager: ^0.9.0+3
  crypto: ^3.0.7
  file_picker: ^8.0.0
  saf_util: ^0.11.0
  saf_stream: ^0.12.2
  material_symbols_icons: ^4.2892.0
  # peerdart: ^0.5.6  # DISABLED: No ARM64 Windows support (flutter_webrtc)
  in_app_review: ^2.0.11
  dart_discord_presence: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4
  slang_build_runner: ^4.12.0
  dart_code_linter: ^3.1.1
  drift_dev: ^2.14.0

# dependency_overrides:  # DISABLED: No ARM64 Windows support
#   flutter_webrtc: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/data/iso_639_codes.json
    - assets/plezy.png
    - assets/go-noto-current-regular.ttf
    - assets/shaders/nvscaler/
    - assets/shaders/anime4k/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/plezy.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/plezy_android_foreground.png"
  adaptive_icon_monochrome: "assets/plezy_monochrome.png"
  macos:
    generate: false
  windows:
    generate: true
  linux:
    generate: true
